export const itemFeatures = [
    "Ablenkend",
    "Auslöser",
    "Deckung",
    "Defensiv",
    "Detonation",
    "Doppelwaffe",
    "Dornen",
    "Durchdringung",
    "Entwaffnend",
    "Entwaffnungsimmunität",
    "Entwaffnungsschutz",
    "Exakt",
    "Ferndistanz",
    "Freihändig",
    "Gehärtet",
    "Improvisiert",
    "Kälteschutz",
    "Kletterhilfe",
    "Kritisch",
    "Lange Waffe",
    "Nahkampftauglich",
    "Paarwaffe",
    "Parierwaffe",
    "Primitiv",
    "Reiterrüstung",
    "Reiterschild",
    "Reiterwaffe",
    "Rückkehrend",
    "Rückstoß",
    "Schadensschwund",
    "Scharf",
    "Schildwall",
    "Stabil",
    "Behinderung",
    "Standfestigkeit",
    "Stumpf",
    "Teilbar",
    "Treffsicher",
    "Umklammern",
    "Umwerfend",
    "Unauffällig",
    "Unhandlich",
    "Vielseitig",
    "Wattiert",
    "Wuchtig",
    "Wurffähig",
    "Wurfkörper",
    "Zerbrechlich",
    "Zweihändig"
] as const ;

export type ItemFeature = typeof itemFeatures[number];