export const modifiers = {
    addsplinter: "splinterpoints +2",
    sturdy: "LP +1",
    resistbody: "KW +2",
    resistmind: "GW +2",
    focuspool: "FO +5",
    highini: "INI -3",
    resistpain: "woundMalus.mod -1",
    resistpain1: "woundMalus.mod -1",
    resistpain2: "woundMalus.mod -1",
    swift: "GSW +1",
    armour1: "handicap.armor.mod -1",
    shield1: "handicap.shield.mod -1",
    armour2: "tickMalus.armor.mod -1",
    shield2: "tickMalus.shield.mod -1",
    flashreflexes: "INI -3",
    goodreflexes: "VTD +1",
    arcanespeed: "GSW +1",
    sprinter: "GSW +1",
    focusregen: "focusRegeneration.multiplier 3",
    liferegen: "healthRegeneration.multiplier 3",
    naturalarmor: "SR +1",
    "schmerzimmunität": "woundMalus.mod -100",
    "schmerzresistenz": "woundMalus.mod -1",
    "schwächlich": "woundMalus.nbrLevels 3",
    "erhöhte fokusregeneration": "focusRegeneration.multiplier 3",
    "erhöhte lebensregeneration": "healthRegeneration.multiplier 3",
    "erhöhter fokuspool": "FO +5",
    "flink": "GSW +1",
    "hoher geistiger widerstand": "GW +2",
    "hoher körperlicher widerstand": "KW +2",
    "robust": "LP +1",
    "verbesserte initiative": "INI -3",
    "zusätzliche splitterpunkte": "splinterpoints +2",
    "stabile magie": "lowerFumbleResult +1",
    "blitzreflexe": "INI -3",
    "gute reflexe": "VTD +1",
    "rüstungsträger i": "handicap.armor.mod -1",
    "rüstungsträger 1": "handicap.armor.mod -1",
    "rüstungsträger ii": "tickMalus.armor.mod -1",
    "rüstungsträger 2": "tickMalus.armor.mod -1",
    "schildträger i": "handicap.shield.mod -1",
    "schildträger 1": "handicap.shield.mod -1",
    "schildträger ii": "tickMalus.shield.mod -1",
    "schildträger 2": "tickMalus.shield.mod -1",
    "natürlicher rüstungsschutz": "SR +1"
} as const ;
export type SplittermondModifier = keyof typeof modifiers;